### ISSUE TITLE
Your description of docker installation does not work.

### ISSUE THREAD

**Issue by kopetsch** [decidim/docker#106]
`git clone git@github.com:decidim/docker.git decidim-docker`
results in 

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Instead I used 
`git clone https://github.com/decidim/docker.git`

it works, but 

`docker-compose up`

throws error:
`docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
`
Trace:
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'

```

Thanks for help.

**Comment by alecslupu** [comment]
This seems to be an issue with your docker environment.

**Comment by kopetsch** [comment]
Sorry, but your answer does not really help.

**Comment by alecslupu** [comment]
> Sorry, but your answer does not really help.

I cannot help, as i do not know your setup , versions etc ... This Ubuntu bug report may be related to your issue: 
https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348 

My initial thought is that you were using an ancient version of docker & docker compose.

**Comment by kopetsch** [comment]
docker-ce is already the newest version (5:27.3.1-1~ubuntu.24.04~noble)
docker-compose is already the newest version (1.29.2-6ubuntu1)

**Comment by kopetsch** [comment]
Please, can you give me a hint, what to do?

**Comment by alecslupu** [comment]
have you checked the issue i gave? 

https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348/comments/18

**Comment by kopetsch** [comment]
Thank you.
I will try out another E-Participation Software.

**Comment by alecslupu** [comment]
@kopetsch you can always try Decidim  in nightly.decidim.org and also on try.decidim.org 

I have closed the issue as the issue you're reporting is not related to Decidim, and most likely no other participatory platform that offers a `docker compose` recepy would actually work on your computer. 

About "what to do" ? Perform the test on an older version of Linux / docker, Install the python3-docker from the ticket ... and so on .. I do not have access to your computer, so i cannot advise fully on the matter.

**Comment by kopetsch** [comment]
Pointless!
a software, which can not deployed within the latest environment, is not suitable for us.
I close this conversation now.
Bye

**Comment by davidbeig** [comment]
Can you try with just `docker compose up`?

[Here ](https://github.com/itzg/docker-minecraft-server/issues/2578) it seems that they are facing the same problem and it results in just a problem with the old `docker-compose` and the new `docker compose` command.

**Comment by kopetsch** [comment]
Thak you very much! It can be so simple. 

But now I catch the next Error, when running `docker compose up`

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/code/vendor/hello-world.sh": stat /code/vendor/hello-world.sh: no such file or directory: unknown
```
seems `/code/vendor/hello-world.sh`is not existing in the image.

**Comment by alecslupu** [comment]
@kopetsch can you make sure that you run before starting the container a `chmod +x ./scripts/hello-world.sh` ? 
I cannot fully reproduce the error you're encounter, but i see that when i do not have enough rights on the file i get `Permission denied`. 

Yes, the error you may be Decidim related. 

Also, please note this Docker image, is actually running Decidim 0.24 (with a release date of Mar 26, 2021). 
Will update the scripts and come back with some new info.

**Comment by alecslupu** [comment]
I cannot reproduce your error

having the following packs installed. Maybe is some kind of setting that i've done some time ago. My installed packages are: 
```
$ apt list --installed | grep docker 

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker-buildx-plugin/noble,now 0.17.1-1~ubuntu.24.04~noble amd64 [installed]
docker-ce-cli/noble,now 5:27.3.1-1~ubuntu.24.04~noble amd64 [installed]
docker-ce-rootless-extras/noble,now 5:27.3.1-1~ubuntu.24.04~noble amd64 [installed,automatic]
docker-ce/noble,now 5:27.3.1-1~ubuntu.24.04~noble amd64 [installed]
docker-compose-plugin/noble,now 2.29.7-1~ubuntu.24.04~noble amd64 [installed]
```

Could you paste somewhere (gist.github.com) the entire output of your `docker compose up` command?
