### ISSUE TITLE
fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /code/Piratas

### ISSUE THREAD

**Issue by ferox** [decidim/docker#58]
Error running docker run -it -v "$(pwd):/code" decidim/decidim ${APP_NAME}

- Docker Version: 19.03.13
- Docker Compose Version: 1.27.4
- OS Version: Fedora 33 with Plasma/KDE
- build: 4484c46

Steps to Reproduce:

1. git clone https://github.com/decidim/docker.git
2. cd docker
3. APP_NAME=Piratas
4. docker run -it -v "$(pwd):/code" decidim/decidim ${APP_NAME}

Output:

```
Status: Downloaded newer image for decidim/decidim:latest
Traceback (most recent call last):
        24: from /usr/local/bundle/bin/decidim:23:in `<main>'
        23: from /usr/local/bundle/bin/decidim:23:in `load'
        22: from /usr/local/bundle/gems/decidim-generators-0.23.1/exe/decidim:35:in `<top (required)>'
        21: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        20: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        19: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        18: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        17: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        16: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        15: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        14: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        13: from (eval):1:in `create_root'
        12: from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/generators/app_base.rb:165:in `create_root'
        11: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:14:in `empty_directory'
        10: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
         9: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:50:in `invoke!'
         8: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
         7: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:52:in `block in invoke!'
         6: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
         5: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
         4: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
         3: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
         2: from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
         1: from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
/usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /code/Piratas (Errno::EACCES)
```

**Comment by oliverbarnes** [comment]
@ferox sorry for the delay. This flow is going to be deprecated in favor of an app image (current decidim:lates is an app generator image). See https://github.com/decidim/docker/discussions/67
